#pragma once

#include "repositories/IActivityRepository.hpp"
#include "repositories/IFactRepository.hpp"
#include "models/Activity.hpp"
#include "models/Fact.hpp"
#include <memory>
#include <cstddef>
#include <optional>
#include <string>

namespace timetracker::services {

class TimeTrackingService {
public:
    TimeTrackingService(
        std::shared_ptr<repositories::IActivityRepository> activityRepo,
        std::shared_ptr<repositories::IFactRepository> factRepo);
    ~TimeTrackingService() = default;

    // Start tracking a new activity (stops any ongoing)
    models::Fact startTracking(const std::string& activityName, const std::string& description = "");

    // Start tracking with a custom start time (stops any ongoing)
    models::Fact startTracking(const std::string& activityName, int64_t startTime, const std::string& description = "");

    // Stop the current tracking
    std::optional<models::Fact> stopTracking();

    // Check if currently tracking
    bool isTracking() const;

    // Get current ongoing fact
    std::optional<models::Fact> getCurrentTracking() const;

    // Manual entry. Set autoGenerated for entries produced by auto-fill, which rebuilds them
    // on every run instead of treating them as user data.
    models::Fact addManualEntry(const std::string& activityName, int64_t startTime, int64_t endTime, const std::string& description = "", bool autoGenerated = false);

    // Edit an existing entry
    void updateEntry(const models::Fact& fact, const std::string& activityName, const std::string& description = "");

    // Delete an entry
    void deleteEntry(int64_t factId);

    // Get recent entries
    std::vector<models::Fact> getRecentEntries(int limit = 10, int offset = 0) const;

    // Get entries for a date range (matches on start time only)
    std::vector<models::Fact> getEntriesForRange(int64_t startTime, int64_t endTime) const;

    // Get every entry whose interval intersects [startTime, endTime), including ones that
    // started earlier and reach into the window
    std::vector<models::Fact> getEntriesOverlappingRange(int64_t startTime, int64_t endTime) const;

    // Look up an activity by name without creating it. The lookup is case-insensitive, and the
    // returned activity carries the name as it is stored, which may differ in case from the
    // argument — compare facts by activity id rather than by name
    std::optional<models::Activity> findActivity(const std::string& activityName) const;

    // Get all activities
    std::vector<models::Activity> getAllActivities() const;

    // Search activities
    std::vector<models::Activity> searchActivities(const std::string& query, int limit = 10) const;

    // Monotonic revision of persisted time-entry data.
    std::size_t getDataRevision() const noexcept { return dataRevision_; }

private:
    std::shared_ptr<repositories::IActivityRepository> activityRepo_;
    std::shared_ptr<repositories::IFactRepository> factRepo_;

    // Cached current tracking state
    mutable std::optional<models::Fact> currentTracking_;
    mutable bool currentTrackingCached_{false};
    std::size_t dataRevision_{0};

    void invalidateCache();
    void onEntriesChanged();
    void refreshCurrentTracking() const;
};

} // namespace timetracker::services
