#pragma once

#include "models/Fact.hpp"
#include <vector>
#include <optional>
#include <cstdint>

namespace timetracker::repositories {

class IFactRepository {
public:
    virtual ~IFactRepository() = default;

    // CRUD operations
    virtual models::Fact create(int64_t activityId, int64_t startTime, std::optional<int64_t> endTime = std::nullopt, const std::string& description = "", bool autoGenerated = false) = 0;
    virtual std::optional<models::Fact> findById(int64_t id) = 0;
    virtual std::vector<models::Fact> findAll() = 0;
    virtual void update(const models::Fact& fact) = 0;
    virtual void remove(int64_t id) = 0;

    // Find ongoing fact (fact with no end time)
    virtual std::optional<models::Fact> findOngoing() = 0;

    // Find facts by date range (inclusive) — filters on start_time only
    virtual std::vector<models::Fact> findByDateRange(int64_t startTime, int64_t endTime) = 0;

    // Find every fact whose interval intersects [startTime, endTime), including facts that
    // started before the window, and the ongoing fact if it started before endTime
    virtual std::vector<models::Fact> findOverlappingRange(int64_t startTime, int64_t endTime) = 0;

    // Find facts by activity
    virtual std::vector<models::Fact> findByActivity(int64_t activityId) = 0;

    // Get recent facts (ordered by start_time descending)
    virtual std::vector<models::Fact> findRecent(int limit = 10, int offset = 0) = 0;

    // Stop ongoing fact by setting end time
    virtual void stopOngoing(int64_t endTime) = 0;

    // Clip end time of any completed fact that would overlap with a new activity starting at startTime
    // (i.e., facts where start_time < startTime AND end_time > startTime)
    virtual void clipFactsOverlappingStart(int64_t startTime) = 0;
};

} // namespace timetracker::repositories
