#pragma once

#include <string>
#include <cstdint>
#include <optional>

namespace timetracker::models {

struct Fact {
    int64_t id{0};
    int64_t activityId{0};
    int64_t startTime{0};                // Unix timestamp
    std::optional<int64_t> endTime;      // Null for ongoing
    bool exportedToYoutrack{false};      // Whether exported to YouTrack
    bool autoGenerated{false};           // Created by auto-fill (rebuilt on every auto-fill run)
    std::string description;             // Per-fact description

    // Cached activity name (not stored in DB, populated by joins)
    std::string activityName;

    Fact() = default;

    Fact(int64_t id, int64_t activityId, int64_t startTime, std::optional<int64_t> endTime = std::nullopt)
        : id(id), activityId(activityId), startTime(startTime), endTime(endTime) {}

    [[nodiscard]] bool isOngoing() const {
        return !endTime.has_value();
    }

    [[nodiscard]] int64_t getDuration() const {
        if (endTime.has_value()) {
            return *endTime - startTime;
        }
        return 0;  // Ongoing facts need current time to calculate duration
    }

    [[nodiscard]] int64_t getDuration(int64_t currentTime) const {
        if (endTime.has_value()) {
            return *endTime - startTime;
        }
        return currentTime - startTime;
    }

    // Check if this fact overlaps with another fact (minute precision)
    // Two facts overlap if: (A.start < B.end AND B.start < A.end)
    // Ongoing facts (no end_time) are excluded from overlap detection
    // Timestamps are converted to minutes (truncated) before comparison
    [[nodiscard]] bool overlapsWith(const Fact& other) const {
        // Skip ongoing facts
        if (!endTime.has_value() || !other.endTime.has_value()) {
            return false;
        }

        // Convert timestamps to minutes (truncate seconds)
        int64_t thisStartMin = startTime / 60;
        int64_t thisEndMin = *endTime / 60;
        int64_t otherStartMin = other.startTime / 60;
        int64_t otherEndMin = *other.endTime / 60;

        // Check for overlap at minute precision: A.start < B.end AND B.start < A.end
        return thisStartMin < otherEndMin && otherStartMin < thisEndMin;
    }

    bool operator==(const Fact& other) const {
        return id == other.id;
    }
};

} // namespace timetracker::models
