name: macOS Build

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install system dependencies
      run: |
        brew install \
          pkg-config \
          gtk+3

    - name: Install Conan
      run: |
        pip3 install conan --break-system-packages

    - name: Detect Conan profile
      run: |
        conan profile detect --force

    - name: Install dependencies
      run: |
        conan install . --build=missing -s build_type=Release -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

    - name: Configure CMake
      env:
        RELEASE_VERSION: ${{ github.ref_name }}
      run: |
        cmake --preset conan-release

    - name: Build
      run: |
        cmake --build --preset conan-release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tempus-macos
        path: |
          build/Release/tempus

    - name: Upload to release
      if: github.event_name == 'release'
      run: |
        mv build/Release/tempus build/Release/tempus-macos-arm64
        gh release upload ${{ github.ref_name }} build/Release/tempus-macos-arm64
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
